name: Docker

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - main

env:
  REGISTRY: registry-gitea.home-infra.weii.cloud
  IMAGE_NAME: ${{ gitea.repository }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Docker Context for Buildx
        run: |
          docker context create builders || docker context use builders

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
        with:
          endpoint: builders
          driver-opts: image=moby/buildkit:latest
          buildkitd-flags: --debug

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ gitea.actor }}
          password: ${{ secrets.PACKAGE_PAT }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6.18.0
        with:
          file: ./Dockerfile
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/buildx-cache,compression=zstd
          cache-to: type=local,dest=/buildx-cache,compression=zstd,mode=max

  update-github-manifests:
    runs-on: ubuntu-latest

    needs: build-push
    if: startsWith(gitea.ref, 'refs/tags/')

    steps:
      - name: Checkout manifests repository
        uses: actions/checkout@v5
        with:
          repository: home-infra/manifests
          path: manifests
          token: ${{ secrets.REPOSITORY_PAT }}

      - name: Setup Git
        run: |
          set -x
          git config --global user.name "Gitea Actions"
          git config --global user.email "actions@gitea.home-infra.weii.cloud"

      - name: Setup kustomize
        run: |
          curl -sL "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          chmod +x ./kustomize
          mv ./kustomize /usr/bin/kustomize

      - name: Update image tag
        working-directory: manifests
        run: |
          export IMAGE_NAME_LOWER=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
          cd kubernetes/apps-autosync/bot-farm/pingu-line-bot
          kustomize edit set image ${{ env.REGISTRY }}/$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]'):${{ gitea.ref_name }}
          git add .
          git commit -m "Update ${{ env.REGISTRY }}/$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]') image to ${{ gitea.ref_name }}"
          git push
